USE master
GO

CREATE DATABASE ThiTracNghiem
GO

USE ThiTracNghiem
GO

CREATE TABLE Lophoc
(
	MaLop CHAR PRIMARY KEY,
	TenLop CHAR
);
GO
CREATE TABLE MonHoc
(
	MaMH CHAR PRIMARY KEY,
	TenMH CHAR
);
GO
CREATE TABLE Chuong
(
	MaChuong CHAR PRIMARY KEY,
	TenChuong CHAR NOT NULL,
	MaMH CHAR,
	CONSTRAINT fk_MonHoc_Chuong FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
);
GO
CREATE TABLE TaiKhoan
(
	MaTK CHAR PRIMARY KEY,
	TenTK VARCHAR NOT NULL,
	MatKhau CHAR NOT NULL,
	Email CHAR NOT NULL,
	GioiTinh BIT NOT NULL,
	NgaySinh DATE NOT NULL,
	LoaiTK CHAR(1) NOT NULL,
	MaLop CHAR,
	CONSTRAINT fk_TaiKhoan_LopHoc FOREIGN KEY (MaLop) REFERENCES LopHoc(MaLop)
);
GO
CREATE TABLE Cauhoi
(
	MaCauHoi CHAR PRIMARY KEY,
	NoiDungCauHoi NVARCHAR NOT NULL,
	DapanA NVARCHAR NOT NULL,
	DapanB NVARCHAR NOT NULL,
	DapanC NVARCHAR NOT NULL,
	DapanD NVARCHAR NOT NULL,
	DapanDung NVARCHAR NOT NULL,
	MaChuong CHAR,
	CONSTRAINT fk_CauHoi_Chuong FOREIGN KEY (MaChuong) REFERENCES Chuong(MaChuong)
);
CREATE TABLE DeThi
(
	MaDeThi CHAR PRIMARY KEY,
	TenDeThi NVARCHAR NOT NULL,
	TGlambai TIME,
	SoLuongCau INT,
	MaCauHoi CHAR,
	CONSTRAINT fk_DeThi_CauHoi FOREIGN KEY (MaCauHoi) REFERENCES CauHoi(MaCauHoi)
);
CREATE TABLE BaiLam
(
	MaBaiLam CHAR PRIMARY KEY,
	MaHS CHAR,
	DapanDaChon NVARCHAR,
	TrangThai BIT,
	CONSTRAINT fk_BaiLam_TaiKhoan FOREIGN KEY (MaHS) REFERENCES TaiKhoan(MaTK)

);
