//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final___OOP.DAO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        public string MaCauHoi { get; set; }
        public string NoiDungCauHoi { get; set; }
        public string DapAnA { get; set; }
        public string DapAnB { get; set; }
        public string DapAnC { get; set; }
        public string DapAnD { get; set; }
        public string DapAnDung { get; set; }
        public string MaChuong { get; set; }
    
        public virtual Chuong Chuong { get; set; }
    }
}
