//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final___OOP.DAO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachLop
    {
        public string MaSV { get; set; }
        public string MaLop { get; set; }
        public string Temp { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual ThongTinSV ThongTinSV { get; set; }
    }
}
