//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final___OOP.DAO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string MaTK { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string LoaiTK { get; set; }
    
        public virtual ThongTinCB ThongTinCB { get; set; }
        public virtual ThongTinSV ThongTinSV { get; set; }
    }
}
