//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final___OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiLam
    {
        public string MaBaiLam { get; set; }
        public string MaSV { get; set; }
        public string DapanDaChon { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual DeThi DeThi { get; set; }
        public virtual ThongTinSV ThongTinSV { get; set; }
    }
}
