//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final___OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cauhoi
    {
        public string MaCauHoi { get; set; }
        public string NoiDungCauHoi { get; set; }
        public string DapanA { get; set; }
        public string DapanB { get; set; }
        public string DapanC { get; set; }
        public string DapanD { get; set; }
        public string DapanDung { get; set; }
        public string MaChuong { get; set; }
    
        public virtual Chuong Chuong { get; set; }
    }
}
