//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final___OOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThiTracNghiemEntities : DbContext
    {
        public ThiTracNghiemEntities()
            : base("name=ThiTracNghiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiLam> BaiLam { get; set; }
        public virtual DbSet<Cauhoi> Cauhoi { get; set; }
        public virtual DbSet<Chuong> Chuong { get; set; }
        public virtual DbSet<DanhSachLop> DanhSachLop { get; set; }
        public virtual DbSet<DeThi> DeThi { get; set; }
        public virtual DbSet<Lophoc> Lophoc { get; set; }
        public virtual DbSet<MonHoc> MonHoc { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<ThongTinCB> ThongTinCB { get; set; }
        public virtual DbSet<ThongTinSV> ThongTinSV { get; set; }
    }
}
