USE master
GO

CREATE DATABASE ThiTracNghiem
GO

USE ThiTracNghiem
GO

CREATE TABLE LopHoc
(
	MaLop VARCHAR(10) PRIMARY KEY,
	TenLop NVARCHAR(256)
);
GO

CREATE TABLE MonHoc
(
	MaMH VARCHAR(10) PRIMARY KEY,
	TenMH NVARCHAR(256)
);
GO

CREATE TABLE Chuong
(
	MaChuong VARCHAR(10) PRIMARY KEY,
	TenChuong NVARCHAR(256) NOT NULL,
	MaMH VARCHAR(10),
	CONSTRAINT FK_Chuong_MonHoc FOREIGN KEY(MaMH)REFERENCES MonHoc(MaMH)
);
GO

CREATE TABLE TaiKhoan
(
	MaTK VARCHAR(10) PRIMARY KEY,
	MatKhau VARCHAR(256) NOT NULL,
	Email NVARCHAR(256) NOT NULL,
	LoaiTK VARCHAR(1) NOT NULL,

);
GO

CREATE TABLE ThongTinCB
(
	MaCB VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR (256) NOT NULL,
	GioiTinh BIT NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(256) NOT NULL
	CONSTRAINT FK_ThongTinCB_TaiKhoan FOREIGN KEY(MaCB)REFERENCES TaiKhoan(MaTK)
);
GO

CREATE TABLE ThongTinSV
(
	MaSV VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR (256) NOT NULL,
	GioiTinh BIT NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(256) NOT NULL,
	CONSTRAINT FK_ThongTinSV_TaiKhoan FOREIGN KEY(MaSV)REFERENCES TaiKhoan(MaTK)
);

GO
CREATE TABLE DanhSachLop
(
	MaSV VARCHAR(10),
	MaLop VARCHAR(10),
	Temp VARCHAR(1),
	PRIMARY KEY (MaSV,MaLop),
	CONSTRAINT FK_DanhSachLop_ThongTinSV FOREIGN KEY(MaSV)REFERENCES ThongTinSV(MaSV),
	CONSTRAINT FK_DanhSachLop_LopHoc FOREIGN KEY(MaLop)REFERENCES LopHoc(MaLop)
);
GO

CREATE TABLE CauHoi
(
	MaCauHoi VARCHAR(10) PRIMARY KEY,
	NoiDungCauHoi NVARCHAR(500) NOT NULL,
	DapAnA NVARCHAR(256) NOT NULL,
	DapAnB NVARCHAR(256) NOT NULL,
	DapAnC NVARCHAR(256)NOT NULL,
	DapAnD NVARCHAR(256) NOT NULL,
	DapAnDung VARCHAR(1) NOT NULL,
	MaMH VARCHAR(10),
	MaChuong VARCHAR(10),
	CONSTRAINT FK_CauHoi_MonHoc FOREIGN KEY(MaMH)REFERENCES MonHoc(MaMH),
	CONSTRAINT FK_CauHoi_Chuong FOREIGN KEY(MaChuong)REFERENCES CHuong(MaCHuong)
);
GO

CREATE TABLE DeThi
(
	MaDeThi VARCHAR(10) PRIMARY KEY,
	TenDeThi NVARCHAR(256) NOT NULL,
	TGLamBai TIME NOT NULL,
	SoLuongCau INT NOT NULL,
	NoiDungDeThi NVARCHAR(MAX) NOT NULL,
	MaCB VARCHAR(10),
	MaLop VARCHAR(10),
	MaMH VARCHAR(10),
	CONSTRAINT FK_DeThi_ThongTinCB FOREIGN KEY(MaCB)REFERENCES ThongTinCB(MaCB),
	CONSTRAINT FK_DeThi_LopHoc FOREIGN KEY(MaLop)REFERENCES LopHoc(MaLop),
	CONSTRAINT FK_DeThi_MonHoc FOREIGN KEY(MaMH)REFERENCES MonHoc(MaMH)
);
GO

CREATE TABLE BaiLam
(
	MaBaiLam VARCHAR(10),
	MaSV VARCHAR(10),
	DapAnDaChon NVARCHAR(MAX),
	TrangThai BIT NOT NULL,
	PRIMARY KEY (MaBaiLam, MaSV),
	CONSTRAINT FK_BaiLam_DeThi FOREIGN KEY(MaBaiLam)REFERENCES DeThi(MaDeThi),
	CONSTRAINT FK_BaiLam_ThongTinSV FOREIGN KEY(MaSV)REFERENCES ThongTinSV(MaSV)
);
--DROP DATABASE ThiTracNghiem

